### ISSUE TITLE
Error during compile: libweston/compositor-wayland.c: free(theme)

### ISSUE THREAD

**Issue by tripzero** [intel/ias#1]
Error follows:

make[1]: Entering directory '/home/tripzero/src/ias'
  CC       libweston/wayland_backend_la-compositor-wayland.lo
libweston/compositor-wayland.c: In function ‘create_cursor’:
libweston/compositor-wayland.c:2532:8: error: ‘theme’ undeclared (first use in this function)
   free(theme);
        ^~~~~

**Comment by satyeshwar** [comment]
Can you please build it this way?
./autogen.sh --disable-libunwind --enable-xkbcommon --disable-systemd-login --disable-wayland-compositor

**Comment by tripzero** [comment]
builds with those options.  Is wayland backend not supported?

**Comment by satyeshwar** [comment]
Yes, we only support our own ias-backend.

**Comment by tripzero** [comment]
Can we add this to the README?

**Comment by satyeshwar** [comment]
Sure, I will add it now.

**Comment by satyeshwar** [comment]
Done. Please check out the latest README. Note that I added a few more options. These are the precise flags with which our integration team builds IAS today so it would be good to continue with the same for CL.

**Comment by satyeshwar** [comment]
Can I mark this issue as closed?

**Comment by tripzero** [comment]
Yes.
