### ISSUE TITLE
Question: Does IAS interface support composing and returning the frame back to client? 

### ISSUE THREAD

**Issue by dextergk** [intel/ias#18]
This is essential for writing to a file and/or broadcasting use case

**Comment by satyeshwar** [comment]
We support two features in IAS:
1) You can always get a screenshot just like open source Weston can by pressing the Print Screen key. Additionally, if you are a root level app, you can also ask IAS to provide you the current frame without needing a keyboard. This is useful if you want just one frame once in a while.
2) We support a remote display use case where IAS passes on a drm prime handle of an app's buffer to a special client called remote-display (https://github.com/intel/ias/tree/master/clients/RemoteDisplay). It can then save it to a file or broadcast. This is useful if you want every single frame that an app is providing continuously.

**Comment by dextergk** [comment]
Thank you!!
