### ISSUE TITLE
out-of-tree libdrm patches required to build

### ISSUE THREAD

**Issue by tripzero** [intel/ias#2]
Regarding commit: d1997bcd836cb9a2f3f1401fb36506680672078c

Patches are reportedly not upstream because upstream has duplicate methods of achieving the same goal.  IAS should be changed to reflect the upstream method.

First patch was submitted here: https://lists.freedesktop.org/archives/intel-gfx/2015-October/078691.html
Second patch[1] was never submitted upstream.

[1] - xf86drmMode-Add-plane-blending-helpers.patch

**Comment by satyeshwar** [comment]
Have reverted plane blending related changes in dev_plane_blend branch. Also, agreed to provide new patches in IAS that conform to the new way that plane blending will be done in DRM and i915

**Comment by tripzero** [comment]
We may want to keep this open until the "new way" is available and can be implemented.

**Comment by tripzero** [comment]
We can close this with the new commit that implements plane blending without libdrm patches.

**Comment by mattcurfman** [comment]
Does this mean the following lines should be removed from the readme?

```
At present, there are two extra patches in libdrm required to 
compile Intel Automotive Solution Compositor for Wayland.
They are:
xf86drmMode-Add-RGBA-property-helpers.patch
xf86drmMode-Add-plane-blending-helpers.patch
```

**Comment by tripzero** [comment]
Yes

**Comment by satyeshwar** [comment]
Yeah I forgot to remove them earlier. I will do it tomorrow.


-------- Original message --------
