### ISSUE TITLE
vmdisplay compiler error.

### ISSUE THREAD

**Issue by YinThong** [intel/ias#27]
I having problem on building vmdisplay application.
this is my autogen.sh parameter.
./autogen.sh --disable-setuid-install --enable-ias-shell --disable-xkbcommon --enable-simple-clients --enable-clients --disable-wayland-compositor --disable-libunwind --disable-xwayland --disable-xwayland-test --disable-x11-compositor --disable-rpi-compositor --enable-ivi-plugin-manager --enable-layer-manager-control --enable-tracing --enable-shadergen --enable-demo-clients-install --enable-vm --enable-vmdisplay

Build error:-
make  all-am
make[1]: Entering directory '/builddir/build/BUILD/ias-4.0.9'
  CC       compositor/ias_weston-main.o
  CC       libweston/libias_4_la-compositor.lo
  CCLD     libias-4.la
  CCLD     ias-weston
  CCLD     vmdisplay-wayland
/usr/bin/ld: ./.libs/libvmdisplay.a(libvmdisplay_la-vmdisplay.o): in function `zwp_linux_dmabuf_v1_create_params':
/builddir/build/BUILD/ias-4.0.9/./protocol/linux-dmabuf-unstable-v1-client-protocol.h:344: undefined reference to `zwp_linux_buffer_params_v1_interface'
/usr/bin/ld: clients/vmdisplay/vmdisplay_wayland-vmdisplay-wayland.o: in function `wl_registry_bind':
/usr/include/wayland-client-protocol.h:1091: undefined reference to `zwp_linux_dmabuf_v1_interface'
/usr/bin/ld: /usr/include/wayland-client-protocol.h:1091: undefined reference to `zwp_linux_dmabuf_v1_interface'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6020: vmdisplay-wayland] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/ias-4.0.9'
make: *** [Makefile:4718: all] Error 2

Suspect there is some miss out library creation on linux-dmabuf.h Please advice.

**Comment by YinThong** [comment]
Sorry just find out the solution last minutes. 
https://github.com/intel/ias/pull/28

Please review. If the patch is good to go please created a release tarball so i will update on clear linux packages/ias.

**Comment by chivakker** [comment]
@YinThong please do not close bugs, once the fixing PR is reviewed and merged it will automatically close the issue.

**Comment by YinThong** [comment]
@chivakker noted

**Comment by satyeshwar** [comment]
Closing this issue manually. Please mention in commit message "Fixes #XYZ" in the future as it will automatically close that issue.
