### ISSUE TITLE
release tag

### ISSUE THREAD

**Issue by tripzero** [intel/ias#3]
IAS needs a release tag.  Release tags mark stable versions of the software. This allows downstream projects to use github's mechanisms for producing tarballs: ie, https://github.com/intel/ias/archive/c83458881f6374fcd81144db542f3d0bd77d920c.tar.gz would give me a tar ball with that hash. The hash can be replaced with a release branch or tag like this: https://github.com/intel/ias/archive/4.0.0.tar.gz

**Comment by satyeshwar** [comment]
okay, I will add a tag ASAP.

**Comment by satyeshwar** [comment]
A tag of 4.0.0 has been pushed

**Comment by satyeshwar** [comment]
Is this one okay to be closed?

**Comment by satyeshwar** [comment]
Closed after agreement with submitter.
