### ISSUE TITLE
vmdisplay-wayland failed to run

### ISSUE THREAD

**Issue by xinyunliu** [intel/ias#37]
while test it with clearlinux and ias, it failed.

```
root@sos ~ # ./vmdisplay-wayland 1 test -i 0 -X 0 -Y 0 -W 800 -H 600
wl_registry@2: error 0: invalid version for global wl_drm (10): have 2, wanted 3
vmdisplay-wayland: clients/vmdisplay/vmdisplay-wayland.c:238: init_egl: Assertion `ret == EGL_TRUE' failed.
Aborted (core dumped)
```
```
root@sos ~ # swupd info
Installed version: 27120
```

**Comment by xinyunliu** [comment]
vmdisplay-wayland can run with this hack temporally. Seems should be fixed in Makefile.am or just remove the dead code which are not used in wl_drm (version 3)

``` diff
diff --git a/clients/vmdisplay/vmdisplay-wayland.c b/clients/vmdisplay/vmdisplay-wayland.c
index f2f210c..1596ec9 100644
--- a/clients/vmdisplay/vmdisplay-wayland.c
+++ b/clients/vmdisplay/vmdisplay-wayland.c
@@ -1083,7 +1083,7 @@ registry_handle_global(void *data, struct wl_registry *registry, uint32_t name,
                ias_hmi_add_listener(d->hmi, &hmi_listener, d);
        } else if (strcmp(interface, "wl_drm") == 0) {
                d->wl_drm =
-                   wl_registry_bind(registry, name, &wl_drm_interface, 3);
+                   wl_registry_bind(registry, name, &wl_drm_interface, 2);
                wl_drm = d->wl_drm;
        } else if (strcmp(interface, "zwp_linux_dmabuf_v1") == 0) {
                d->wl_dmabuf =
diff --git a/clients/vmdisplay/wayland-drm-protocol.c b/clients/vmdisplay/wayland-drm-protocol.c
index 71e259a..30b752b 100644
--- a/clients/vmdisplay/wayland-drm-protocol.c
+++ b/clients/vmdisplay/wayland-drm-protocol.c
@@ -96,7 +96,7 @@ static const struct wl_message wl_drm_events[] = {
 };

 WL_EXPORT const struct wl_interface wl_drm_interface = {
-       "wl_drm", 3,
+       "wl_drm", 2,
        5, wl_drm_requests,
        4, wl_drm_events,
 };
```

**Comment by xinyunliu** [comment]
@armurthy @satyeshwar, any idea on how to fix it?

**Comment by satyeshwar** [comment]
I am really surprised where this version 3 of wl_drm came from. wl_drm is a protocol that comes from Mesa. (https://github.com/mesa3d/mesa/blob/master/src/egl/wayland/wayland-drm/wayland-drm.xml), and even in the latest version of mesa, the version number is only 2. So the right thing to do would be to build mesa, then copy wayland-drm-client-protocol.h and wayland-drm-protocol.c from there into vmdisplay and change vmdisplay-wayland.c to use version 2 instead of 3.

**Comment by tripzero** [comment]
@satyeshwar , isn't your suggestion exactly what @xinyunliu has already done in the above patch?  If so, @xinyunliu , can you submit PR?

**Comment by satyeshwar** [comment]
yeah, please submit a PR if you can, which uses version 2.

**Comment by xinyunliu** [comment]
@tripzero @satyeshwar ,  No, I won't submit PR as above. It's only a workaround and may break others. The owner should be more familiar with that part of code and provide a better fix.

**Comment by tripzero** [comment]
@xinyunliu, If satyeshwar doesn't see a problem with the changes made to vmdisplay, you should feel comfortable submitting the PR.

**Comment by satyeshwar** [comment]
That's okay, I can do it myself. no problems.

**Comment by tripzero** [comment]
@xinyunliu can you confirm fix?

**Comment by tripzero** [comment]
@satyeshwar looks like e66266d did not fix the wl_drm case.  Only changed to version 2 for zwp_linux_dmabuf_v1_interrface.  Shouldn't the fix be a few lines up in vmdisplay-wayland.c?
