### ISSUE TITLE
vmdisplay: remove dead code for YOCTO

### ISSUE THREAD

**Issue by xinyunliu** [intel/ias#38]
there is  code snippet for yocto specific, is it need to be cleaned up?

``` diff
diff --git a/clients/vmdisplay/vmdisplay.h b/clients/vmdisplay/vmdisplay.h
index 390b26c..56eea73 100644
--- a/clients/vmdisplay/vmdisplay.h
+++ b/clients/vmdisplay/vmdisplay.h
@@ -40,12 +40,7 @@ typedef int32_t s32;
 #include <GLES2/gl2.h>
 #include <EGL/egl.h>
 #include <EGL/eglext.h>
-#ifdef YOCTO_BUILD
-#include <igvtg-kernel-headers/i915_drm.h>
-#include <igvtg-kernel-headers/drm.h>
-#else
 #include <libdrm/drm.h>
-#endif
 #include "vm-shared.h"
 #include "vmdisplay-shared.h"
```

**Comment by satyeshwar** [comment]
well, we still need to make sure that vmdisplay builds for Yocto so can't remove this one just yet. If there is no other concern from your side, I would like to close this comment.

**Comment by xinyunliu** [comment]
Got it, you can close this issue. 
I found it through code review while try to resolve https://github.com/intel/ias/issues/37. And seems not related.

**Comment by xinyunliu** [comment]
Close the issue since the code is still needed for Yocto. Hope Makefile.am refresh related changes.
