### ISSUE TITLE
Application got struck while moving horizontally by 1 pixel

### ISSUE THREAD

**Issue by oidapala** [intel/ias#41]
Use the config to launch ias: https://github.com/intel/ias/blob/master/ias.conf.example
Create a test application
Using a second application connect to ias-hmi interface.
Using the id of the test application move it to 0 x 0.
Move the application horizontally by 1 pixel at a time and keep y axis at 0 to the edge of the screen 
Application got struck after 30 to 40 pixels moves and observed below error in systemctl log
 
Run "systemctl status ias-earlyapp.service"
Nov 28 07:16:37 SOS_20181121-26400 ias-weston-launch[13731]: [07:16:37.037] Failed to generate shader binary
Nov 28 07:20:31 SOS_20181121-26400 ias-weston-launch[13731]: [07:20:31.969] IAS ERROR: Queueing atomic pageflip failed: No such file or directory

**Comment by satyeshwar** [comment]
I can't find ias-earlyapp.service on my file system. I also swupd search ias-earlyapp.service and couldn't find it in any bundles. Where did you get it from? 
What version of IAS did you try? I fixed a defect around atomic pageflip in https://github.com/intel/ias/tree/4.0.14
Can you please try this version and let me know if you can still reproduce this issue?

**Comment by satyeshwar** [comment]
Hello, can you please let me know if this issue is still reproducible? If not, then please close this defect. Thanks!

**Comment by oidapala** [comment]
Hi Satyeshwar, Allow us sometime I will verify and update.

**Comment by oidapala** [comment]
This issue is not observed with latest  version as suggested by Satyeshwar. we can close
