### ISSUE TITLE
Undefined symbol issue

### ISSUE THREAD

**Issue by abhijithota** [intel/ias#5]
Hi Satyeshwar,

1. We are currently building ias Weston for our Apollo Lake based system (through a Yocto project). We are getting the issue of undefined reference to wet_get_config. Would be helpful if you can let us know the library that provides the same. The error message is as below.

> Loading module '/usr/lib/weston/desktop-shell.so'
> Failed to load module: /usr/lib/weston/desktop-shell.so:  undefined symbol: wet_get_config

**Comment by satyeshwar** [comment]
Again, you are not using ias-shell. I provided weston.ini contents to you last time.
-Satyeshwar



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by armurthy** [comment]
There are multiple shells, like xdg shell, desktop shell and the one that we have developed is ias_shell.
We are supporting ias_shell and hence the same has the be enabled in weston.ini
Something like 
shell=ias-shell.so

**Comment by abhijithota** [comment]
Thanks for info. We are using ias-shell now and running weston. We are using 2 HDMI output to run 2 different application, so we modified the ias.conf to have both the HDMI CRTC (as specified in the ias.conf.txt file attached). However,

1. We are getting an error message from Weston stating **IAS ERROR: Queueing pageflip failed: No such file or directory**. I tried changing use_nuclear_flip to 0 but it did not solve the issue. PFA the file log.txt for the complete output. Would be great if you can specify some leads for the cause and a possible resolution.

2. Is there a way to specify the ias-shell to start an application at a fixed location?

Thanks

[ias.conf.txt](https://github.com/intel/ias/files/2330357/ias.conf.txt)
[log.txt](https://github.com/intel/ias/files/2330358/log.txt)

**Comment by armurthy** [comment]
1. " IAS ERROR: Queueing pageflip failed: No such file or directory" This error will come only while using the legacy page flip and not while using atomic page flip. Note that we have to use atomic page flip only and hence always have "use_nuclear_flip=1" in ias.cong. The logs that you shared are with disabling the nuclear page flip. Please share the logs with nuclear page flip enabled.

2. You can start any app at any location during the boot by adding them to the systemd service.

**Comment by abhijithota** [comment]
Thanks for the quick reply.

For the 2nd question in my previous message, I wanted to know how can we specify the position of every application being launched to a specific location on the screen. Can we do that using ias config file? Initially, we used to do this through desktop-shell by setting the coordinates through weston_view_set_initial_position() call.

Also, is there a way to set the background with ias-shell? Something similar to setting the background-image and background-type with weston.ini. Will that work?

Thanks

**Comment by armurthy** [comment]
Position of the apps can be changed by using "surfctrl", This "surfctrl" should be available on compiling the ias weston. 
Change the position of apps using surfctrl: surfctrl --surfname="your_app_name" --pos=axb (where a and b are the new x,y co-ordinates)

For setting background, ias_test_hmi client can be used. For more info you can look into the ias_shell_set_background() API.

**Comment by satyeshwar** [comment]
Hi Abhijit,
Can you please add:
i915.nuclear_pageflip=1 in your kernel command line as well?
-Satyeshwar

**Comment by satyeshwar** [comment]
Hi Abhijit,
Do you still have a problem or can I close this issue?
-Satyeshwar

**Comment by abhijithota** [comment]
Hi Satyeshwar,

Would be great if we can keep this thread open for a week. Trying things from my side and would take some time to manage them all.

Else, please let me know if closing this and opening a new one later (if required) would be a good idea.

Thanks,
Abhijit

**Comment by satyeshwar** [comment]
Abhijit,
We can't keep a thread open if the original issue is resolved. It is not meant to be overloaded for any issues that you find with IAS. 
Please confirm that your original issue is gone so that we may close this one. If you have further problems, please open a new issue.

**Comment by abhijithota** [comment]
Hi Satyeshwar and Arun,

Yes, we have solved the original issue titled in this thread. Please close the same.

Thanks a lot for your help.
