### ISSUE TITLE
e4707ed34da3682001c8b017a02b5738c5220949 causes regression on some hardware

### ISSUE THREAD

**Issue by tripzero** [intel/ias#53]
When running ias-weston in a hypervisor environment, applications that run at 1920x1080 cannot display on hardware with gen 9 intel graphics.  Application in this situation is using too many ddb blocks than exist per-plane.  Reverting e4707ed34da3682001c8b017a02b5738c5220949 solves the issue, but is not a "real fix".

**Comment by chivakker** [comment]
+1 to reverting till a solution is found.

**Comment by satyeshwar** [comment]
This issue is fixed with 09466b2bb4bb966809ecb9b6ee91cf3e3cc9165c
