### ISSUE TITLE
vmdisplay: fd leaks

### ISSUE THREAD

**Issue by xinyunliu** [intel/ias#59]
https://github.com/intel/ias/blob/master/clients/vmdisplay/vmdisplay.c#L441
				} else {
					printf("DRI not supporint NV12\n");
                                         // should close fd, other wise leaks happen
                                         // close(dmabuf_fd);
					return;
				}

**Comment by downor** [comment]
https://github.com/intel/ias/pull/60 should take care of this problem.
Thanks for reporting this.

**Comment by xinyunliu** [comment]
The fix is better than I proposed.  Thanks!

**Comment by satyeshwar** [comment]
#60 has been merged in so I am closing this issue.
