### ISSUE TITLE
Setting the surface to full-screen for app

### ISSUE THREAD

**Issue by abhijithota** [intel/ias#6]
Hi,

I wanted to know if there is any utility / client app to set a particular surface to be full-screen in ias shell, without any decorations or top toolbar?

Also, is the fullscreen implementation bind to the wayland interface to be used by GUI frameworks?

Thanks

**Comment by satyeshwar** [comment]
https://github.com/intel/ias/blob/master/clients/simple-egl.c#L478

Not sure I understand your second question though. The fullscreen request that we have is for an ias_surface. It is a standard Wayland request. It can be used by any apps or frameworks.

**Comment by satyeshwar** [comment]
The previous answer was about how a surface can request to be made fullscreen by the compositor. If you need a central utility to make some other surface full screen, then you can use surfctrl. It can resize another app. However the way that it works is that surfctrl requests IAS to reconfigure the app buffer to be the size of the output. IAS in turn, sends an event to the original client app whose surface is being reconfigured. So the original app must support resizing of its buffers to match the new size that the compositor is providing to it. If it doesn't do that, then there would be no impact.
You can see the source code of surfctrl here: https://github.com/intel/ias/blob/master/clients/surfctrl.c
For an example of an app that correctly reconfigures its buffers to match the new size that the compositor expects, please look at simple-egl: https://github.com/intel/ias/blob/master/clients/simple-egl.c#L394

-Satyeshwar

**Comment by satyeshwar** [comment]
Can I close this defect if I have answered all of your questions?

**Comment by abhijithota** [comment]
Hi Satyeshwar, thanks for your help, this was valuable. I am closing the issue now.
